//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrLinkedDictionary.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrLinkedDictionary.Res.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array is null..
        /// </summary>
        internal static string ARRAY_IS_NULL {
            get {
                return ResourceManager.GetString("ARRAY_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single dimensional arrays are supported for the requested action..
        /// </summary>
        internal static string ARRAY_MUST_SINGLE_DIMENSIONAL {
            get {
                return ResourceManager.GetString("ARRAY_MUST_SINGLE_DIMENSIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert new item after specified item because dictionary does not have element with key &apos;{0}&apos;..
        /// </summary>
        internal static string CANNOT_INSERT_AFTER_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CANNOT_INSERT_AFTER_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot insert new item before specified item because dictionary does not have element with key &apos;{0}&apos;..
        /// </summary>
        internal static string CANNOT_INSERT_BEFORE_KEY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CANNOT_INSERT_BEFORE_KEY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rebuild links for item &apos;{0}&apos;..
        /// </summary>
        internal static string CANNOT_REBUILD_LINKS_FOR_ITEM {
            get {
                return ResourceManager.GetString("CANNOT_REBUILD_LINKS_FOR_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rebuild links for item with null key.
        /// </summary>
        internal static string CANNOT_REBUILD_LINKS_KEY_IS_NULL {
            get {
                return ResourceManager.GetString("CANNOT_REBUILD_LINKS_KEY_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot rebuild links because value is null..
        /// </summary>
        internal static string CANNOT_REBUILD_LINKS_VALUE_IS_NULL {
            get {
                return ResourceManager.GetString("CANNOT_REBUILD_LINKS_VALUE_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictonary cannot be null..
        /// </summary>
        internal static string DICTIONRY_NOT_NULL {
            get {
                return ResourceManager.GetString("DICTIONRY_NOT_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string INCORRECT_TYPE {
            get {
                return ResourceManager.GetString("INCORRECT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index is incorrect..
        /// </summary>
        internal static string INDEX_IS_INCORRECT {
            get {
                return ResourceManager.GetString("INDEX_IS_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key must not be null..
        /// </summary>
        internal static string KEY_NOT_BE_NULL {
            get {
                return ResourceManager.GetString("KEY_NOT_BE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutating this collection is not supported because this collection is read-only..
        /// </summary>
        internal static string MUTATING_COLLECTION_IS_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MUTATING_COLLECTION_IS_NOT_SUPPORTED", resourceCulture);
            }
        }
    }
}
