//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrData.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Msg {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Msg() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrData.Res.Msg", typeof(Msg).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not add this node &apos;{0}&apos; as it belongs to another parent node..
        /// </summary>
        internal static string CANNOT_ADD_NODE_BELONG_TO_ANOTHER_PARENT_NODE {
            get {
                return ResourceManager.GetString("CANNOT_ADD_NODE_BELONG_TO_ANOTHER_PARENT_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not add yourself &apos;{0}&apos; as a child node..
        /// </summary>
        internal static string CANNOT_ADD_YOURSELF_AS_CHILD {
            get {
                return ResourceManager.GetString("CANNOT_ADD_YOURSELF_AS_CHILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; is incorrect HEX string..
        /// </summary>
        internal static string INCORRECT_HEX {
            get {
                return ResourceManager.GetString("INCORRECT_HEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The node name &apos;{0}&apos; is incorrect. The node name cannot contain &apos;/&apos; character. As not well as having a name equal to one &apos;.&apos; or two &apos;..&apos; points..
        /// </summary>
        internal static string INCORRECT_NODE_NAME {
            get {
                return ResourceManager.GetString("INCORRECT_NODE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path cannot be null.
        /// </summary>
        internal static string NULL_PATH_ERR {
            get {
                return ResourceManager.GetString("NULL_PATH_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object type &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string OBJ_TYPE_IS_INCORRECT {
            get {
                return ResourceManager.GetString("OBJ_TYPE_IS_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect data type, the specified data should be array..
        /// </summary>
        internal static string OBJ_TYPE_SHOULD_BE_ARRAY {
            get {
                return ResourceManager.GetString("OBJ_TYPE_SHOULD_BE_ARRAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current value with the name &apos;{0}&apos; is overwritten with the new value &apos;{1}&apos;..
        /// </summary>
        internal static string OVERWRITE_EXISTS_VALUE {
            get {
                return ResourceManager.GetString("OVERWRITE_EXISTS_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current value named &apos;{0}&apos; exists and will be preserved..
        /// </summary>
        internal static string PRESERVE_EXISTS_VALUE {
            get {
                return ResourceManager.GetString("PRESERVE_EXISTS_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to rise above the root node. The specified path &apos;{0}&apos;  is incorrect..
        /// </summary>
        internal static string RISE_ABOVE_ROOT_NODE {
            get {
                return ResourceManager.GetString("RISE_ABOVE_ROOT_NODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified type &apos;{0}&apos; is not Enum..
        /// </summary>
        internal static string TYPE_IS_NOT_ENUM {
            get {
                return ResourceManager.GetString("TYPE_IS_NOT_ENUM", resourceCulture);
            }
        }
    }
}
